FROM python:3.12-slim

# Configuración de Python
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Directorio de trabajo
WORKDIR /app

# Dependencias necesarias para mysqlclient
RUN apt-get update && apt-get install -y \
    build-essential \
    default-libmysqlclient-dev \
    pkg-config \
    && rm -rf /var/lib/apt/lists/*

# Instalar uv
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

# Instalar dependencias
COPY pyproject.toml uv.lock ./

RUN uv sync --no-dev --frozen

# Copiar el proyecto
COPY . .

EXPOSE 5000

CMD ["uv", "run", "flask", "--app", "run.py", "run", "--host=0.0.0.0", "--port=5000"]
